import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/configs/styles/Home.module.css';
import Link from 'next/link';
const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>NextJS Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div
          style={{
            position: 'absolute',
            top: '50%',
            left: '50%',
            transform: 'translate(-50%,-50%)',
            display: 'flex',
            gap: '0 0.2rem',
          }}
        >
          This Boilerplate was created by
          <Link
            style={{ cursor: 'pointer', textDecoration: 'underline' }}
            href={'https://github.com/joaovictor-ferreira'}
            target="_blank"
          >
            João Ferreira.
          </Link>
          {';)'}
        </div>
      </main>
    </>
  );
}
