import Head from 'next/head';
import Link from 'next/link';
import { Header } from '@/presentation/components/Header/Header';

export default function Home() {
  return (
    <>
      <Head>
        <title>Campus Pass</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Header />
      </main>
    </>
  );
}
